<?php

namespace Database\Seeders;

use App\Models\Admin;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuperAdminSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Purana data delete karne ke liye (Optional)
        // Admin::truncate(); 

        $users = [
            [
                'id' => 1,
                'name' => 'Ashish',
                'email' => 'superadmin@example.com',
                'password' => '$2y$12$e8SIpWDPCXUq0.wsYyC0DeAuqAaItcWiyR7e/3ViU7tfRzmlv2Usy',
                'remember_token' => 'BsfV3BSrg8Rxo80jbJWAhczP3aoXIhnPcuZCAw5FPuXh2NngptNSd4W4akvT',
                'is_super' => true,
                'phone_number' => '0000000000',
                'country_code' => '+91',
                'address' => null,
                'country' => null,
                'state' => null,
                'city' => null,
                'pincode' => null,
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 15:34:38',
                'updated_at' => '2025-12-16 15:34:38',
            ],
            [
                'id' => 3,
                'name' => 'Vidhi Bharakhada',
                'email' => 'vidhi@omgemsindia.com',
                'password' => '$2y$12$hq4NbNmkLziaFLPjnnZkp.WS2Kn07G76CSFuZq8BH/LaD.y1eJem6',
                'remember_token' => null,
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'Mota Varachha Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'Surat',
                'pincode' => '394101',
                'aadhar_front_image' => 'admins/458a3263-0a4e-48a5-a2ef-9edbba6b8533.png',
                'aadhar_back_image' => 'admins/67dced42-797f-4832-8aff-29d2e1c54b44.png',
                'bank_passbook_image' => 'admins/af547ddd-70d2-44da-8cf2-00e0f9350ba0.png',
                'created_at' => '2025-12-16 17:10:38',
                'updated_at' => '2025-12-16 18:02:13',
            ],
            [
                'id' => 4,
                'name' => 'Harsh',
                'email' => 'harsh@omgemsindia.com',
                'password' => '$2y$12$jG9l469.rVlKkZvfl2/EUu/ojpGJdKEEQjmfQayPNOe0u/Vq6l1I.',
                'remember_token' => null,
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'AMROLI Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'Surat',
                'pincode' => '394107',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:12:31',
                'updated_at' => '2025-12-16 17:54:49',
            ],
            [
                'id' => 5,
                'name' => 'Abhishek',
                'email' => 'abhishek@omgemsindia.com',
                'password' => '$2y$12$kc81.8An8L9f4ohj0EcWpuU2A0jEjeU8cHCe2wWGxHMbdkv.Cnpwu',
                'remember_token' => null,
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'Mota Varachha Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'Surat',
                'pincode' => '394101',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:13:33',
                'updated_at' => '2025-12-16 17:13:33',
            ],
            [
                'id' => 6,
                'name' => 'Trushna',
                'email' => 'trushna@omgemsindia.com',
                'password' => '$2y$12$zUW/iKrIIGlEBG6awV69U..7eJWBTXXyLY1MCJK1SgRArYe63rHsu',
                'remember_token' => '1ESBbVSjnHM9fPKlnz3v7fMSC7Sl4EzMkQaB5TEi9Gm2CbFn6rDxgJVCA1sJ',
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'SURAT',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:16:06',
                'updated_at' => '2025-12-16 17:16:06',
            ],
            [
                'id' => 7,
                'name' => 'Anjali',
                'email' => 'anjali@omgemsindia.com',
                'password' => '$2y$12$V/28qamfgQvHeu25rUo2PubN5hzhu74J6sZ2.VT1ejjVaMwnDyg.q',
                'remember_token' => 'pPdelQOrnVzYudXucjkEChLwq0pscIYVGs5vGxRgLvlYVlWJ7ZlUZF1mIAhq',
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'SURAT',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:18:15',
                'updated_at' => '2025-12-16 17:18:15',
            ],
            [
                'id' => 8,
                'name' => 'Dhruvi',
                'email' => 'dhruvi@omgemsindia.com',
                'password' => '$2y$12$hYMv9VRKGbRnKFxa8FaPnOSXPnWYZLeWCQdWruX/uhMKAs8XsZsYa',
                'remember_token' => 'CLgJSbDx3VsTOYIt91Umc88CJnnxPj7OKEyNq2ZIF0A1EE95AE8bRvhTvvtP',
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'SURAT',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:19:45',
                'updated_at' => '2025-12-16 17:19:45',
            ],
            [
                'id' => 9,
                'name' => 'Shruti',
                'email' => 'shruti@omgemsindia.com',
                'password' => '$2y$12$EvYZae7n9mlTWDPz/.6TEerndXTfAyAedJzuB/8xHLMcljq4sdkVO',
                'remember_token' => 'VK1httHSN4cVRKKeAU8RbMGreqARlDoshueDucTdASxcK22ixwZgj13HfY6X',
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'Surat',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:21:12',
                'updated_at' => '2025-12-16 17:21:12',
            ],
            [
                'id' => 10,
                'name' => 'Bhavin',
                'email' => 'bhavin@omgemsindia.com',
                'password' => '$2y$12$h217iHQ4NqBXmwiXMkIKzO5ZVxMNXwCKbl6GUSDJ1JLyupod8UC/O',
                'remember_token' => null,
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'Surat',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:22:38',
                'updated_at' => '2025-12-16 17:22:38',
            ],
            [
                'id' => 11,
                'name' => 'Janvi Nakrani',
                'email' => 'janvi@omgemsindia.com',
                'password' => '$2y$12$WgjMYEovUSm7BeSI/tvWO.HmjsvgsgK.26VAqZbKvH/y/zEFPBg56',
                'remember_token' => null,
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'Armida Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'SURAT',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:31:42',
                'updated_at' => '2025-12-16 17:31:42',
            ],
            [
                'id' => 12,
                'name' => 'Khushi Patel',
                'email' => 'khushi@omgemsindia.com',
                'password' => '$2y$12$esxLP1Zj.GBQkA2PKlRio.zCsrpqt/rB8Rm51EpNQxIUqwAJ5sZiu',
                'remember_token' => 'rQ7g4JVT8crtC6pzSPyhWBWuDLvrY178qxAdnevnBke2GiKa9K9DhFM1yGTN',
                'is_super' => false,
                'phone_number' => '9876543210',
                'country_code' => null,
                'address' => 'Armida Surat',
                'country' => 'India',
                'state' => 'Gujarat',
                'city' => 'SURAT',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 17:33:38',
                'updated_at' => '2025-12-16 17:33:38',
            ],
            [
                'id' => 13,
                'name' => 'MItesh Sangani',
                'email' => 'mitesh@omgemsindia.com',
                'password' => '$2y$12$e8SIpWDPCXUq0.wsYyC0DeAuqAaItcWiyR7e/3ViU7tfRzmlv2Usy',
                'remember_token' => 'ndZYOEZRabCGWarQCvFoqYvogqWlZQOnYhNG427D03y44qqKs9UjJGdDrHjB',
                'is_super' => true,
                'phone_number' => '7698279481',
                'country_code' => null,
                'address' => 'Armida Surat',
                'country' => 'India',
                'state' => 'gujarat',
                'city' => 'surat',
                'pincode' => '395006',
                'aadhar_front_image' => null,
                'aadhar_back_image' => null,
                'bank_passbook_image' => null,
                'created_at' => '2025-12-16 18:04:43',
                'updated_at' => '2025-12-16 18:04:43',
            ],
        ];

        foreach ($users as $user) {
            Admin::updateOrCreate(
                ['email' => $user['email']],
                $user
            );
        }
    }
}